[profile.default]
src = 'contracts'
libs = ['lib']
out = 'out'
solc_version = '0.8.23'
evm_version = 'shanghai'
optimizer_runs = 1000
bytecode_hash = 'none'

block_number = 120000
block_timestamp = 1640000000
gas_limit = 9223372036854775807 # the gas limit in tests
block_base_fee_per_gas = 100
fs_permissions = [{ access = "read-write", path = "./"}]
ffi=true

[lint]
lint_on_build = false
